### ISSUE TITLE
Weird class names in autocomplete

### ISSUE THREAD

**Issue by kaestlyn** [docura-io/vscode-cm#2]
CM is sending these back as a class `ClassName{}`.i I have no idea why... Happens on some classes for some reason

**Comment by duncr** [comment]
Usually that means it's of `Set` type.
`pln(new (int{})().class); // output: int{}`

**Comment by kaestlyn** [comment]
Would it still return these if I just ask for the classes inside a package though? So If I am running the code like in the cmLiveIndexer.ts file:

``` java
str[] items = ["custom.whatever"];
symbol{} symbols();
for( s in items ) {
    symbols << s.symbol;
} 
for( c in classes( symbols, {symbol:}, includeAllParents=true) ) {
   pln(c.name);
}
```

I just figured this would return only the defined classes such as `public class whatever {}` not return types / members

**Comment by duncr** [comment]
Ya, those are a Collection of some kind and would be compiler-generated.
you can filter those out by looking at the `.src`. where `.src.pos` will be `-1` if it was generated

```
public str[] classNames(str[] items) {
    str[] classes();
    symbol{} symbols();
    for (s in items) symbols << s.symbol;
    for (c in classes(symbols, {symbol:}, includeAllParents=true)) {
        if (c.src.pos > -1) {
            classes << c.name;
        }
    }
    return classes;
}
```

**Comment by kaestlyn** [comment]
Awesome, seems a lot more correct then my current `!c.name.contains("{}")` :smile:
