### ISSUE TITLE
Wrong coloring for "angle" and "point" keywords

### ISSUE THREAD

**Issue by acauan** [docura-io/vscode-cm#21]
![image](https://cloud.githubusercontent.com/assets/17884044/14788727/ac2caf46-0adf-11e6-9a27-d61a81bc392c.png)

![image](https://cloud.githubusercontent.com/assets/17884044/14788758/d6953d34-0adf-11e6-91ac-9447bba78c35.png)

![image](https://cloud.githubusercontent.com/assets/17884044/14788777/ec89382a-0adf-11e6-83d3-2d928c417033.png)

**Comment by kaestlyn** [comment]
point and angle need to be added as primitives to the CM.plist language definition.

**Comment by kaestlyn** [comment]
The .point is an interesting thing, I'm going to consider it a non-issue, because of type casting via the .type syntax:

``` java
int x = 5;
str s = x.str;
```
