### ISSUE TITLE
User Defined Scripts

### ISSUE THREAD

**Issue by kaestlyn** [docura-io/vscode-cm#42]
An idea I've had was to have a specifically named CM file that has a list of void functions, and the extension could read all the functions in that file and then expose them threw the `F1` menu in VSCode to allow the user to run those functions at any time.  Could be useful in a workspace to have cache clearing code for development etc.

**Comment by AlexFielder** [comment]
If I understand you correctly, it would be something like these lines stored in our t.cm file:
`//cm.runtime.util.compileAllBelow(cm.io.cmNative("custom/yourExtensionName/"), reportUnused=false);`

Would that be correct?

**Comment by kaestlyn** [comment]
Sort of, was thinking you could define the file in your vscode config, and vscode would find each function in that file and actually put those in the F1 menu of VScode so you could have something like:
```java
public void cleanUpCache() {
    // whatever code you need here
}
```

And then in VSCode in the F1 commands you'd have `CM: cleanUpCache` so you could easily run that. 

We were thinking we could have 2 levels of this, one at the user level, and one at the workspace level.  That way for a specific CM extension you might have some helpful CM code macros for that project that could be easily ran.  We always seem to have a few `{ ... }` blocks at the end of files that relate to some cache clearing and things like that, so might be nice to have a proper way to run those much easier.
