### ISSUE TITLE
Start CM Fails

### ISSUE THREAD

**Issue by evanlalo** [docura-io/vscode-cm#53]
I've installed the extension and opened my extension folder. When I try to start CM through F1, I receive the following error.

`Command failed: cm_pskill /name "_cm.exe" /beginsWith "msdev" /beginsWith "link" /titleBeginsWith "Microsoft Visual" 'cm_pskill' is not recognized as an internal or external command, operable program or batch file.`

I have tried uninstalling and reinstalling the extension and it still does not work.

Thanks!

**Comment by kaestlyn** [comment]
In your VSCode settings (Ctrl+,) if you look under CM Configuration, what is your `Root` value set to? If its not set as `auto` you should fill it as auto:

![image](https://user-images.githubusercontent.com/1458549/50796891-ac816180-1298-11e9-948a-7b6f47894f8f.png)

I could've swore I had `auto` as the default, but its not.  I'll make sure to get this corrected in the next version of the extension.

Also checkout https://github.com/docura-io/vscode-cm/blob/master/docs/setup.md for help getting the extension setup and https://github.com/docura-io/vscode-cm/blob/master/docs/features.md for feature explanations (I'm working on making this page have more information)

**Comment by evanlalo** [comment]
That seems to have fixed it. Thanks for the quick reply!
