### ISSUE TITLE
Indentation broken intermittently

### ISSUE THREAD

**Issue by AlexFielder** [docura-io/vscode-cm#55]
Hi folks,

Firstly, let me start by saying that this extension has been **an absolute lifesaver** for me over the two years since I first found it! (Emacs can go and die in the tar pit it crawled out of!)

That being said, as the title states, there's an issue I'd been merrily ignoring until a new colleague started using VSCode this morning that I hope is fixable here:

Occasionally, a file edited in VSCode will lose the indentation in Emacs. Which (whilst not critical) leads to situations where the formatting gets screwed-up.

A while back (when I first pointed [hound](https://github.com/hound-search/hound) at the cet data) I noticed that vast swathes of the core cm files are encoded in ANSI instead of UTF-8; could that have a bearing on things?

We recently moved from Perforce to gitlab so I _think_ the issue may resolve itself in time, but would appreciate any feedback you can offer.

(I'm working on sourcing a .cm file that exhibits the problem)

Thanks,

Alex.

**Comment by AlexFielder** [comment]
Sample file:

[moCableBasket.zip](https://github.com/docura-io/vscode-cm/files/3313919/moCableBasket.zip)

Indentation issue occurs on line 440

**Comment by kaestlyn** [comment]
I'd have to really dig in to see what EMACS is doing, in notepad++ I can see see the following snapper.cm for example:

![image](https://user-images.githubusercontent.com/1458549/60054424-1f906000-96a0-11e9-951d-240ca06a1ac8.png)

The methods of the class are indented by 4 spaces, and then the contents of the method are indented by a single tab.

I see roughly the same thing in the file you sent.  Perhaps EMACs has a single tab setup to be 8 spaces?  It looks like that could be the case as something indented 3 times if you look at a core cm file, it will be a TAB and then 4 spaces, and something indented 4 times is represented by 2 TABs.  Seems like it maybe uses 4 spaces to represent a SINGLE indentation and a tab character to represent 2 indentations (what you see)

EDIT: Used the word indent to clarify

**Comment by AlexFielder** [comment]
Thanks for looking into this on our behalf. I am shortly moving on from CET to other things, but how can we remedy this formatting error? Is it a case of changing the default tab in vscode so it matches that of EMACS? (Is that even possible?)

**Comment by kaestlyn** [comment]
I tried to do a little digging, and it seems like with VSCode it's pretty much either tabs or spaces for your indentation.  You would probably have to reach out on github.com/microsoft/vscode and see if its possible to mix tabs and spaces in VSCode with a different size defined for each.

**Comment by kaestlyn** [comment]
This is old, but I'm going to close this as there is now a feature in VSCode that you can have Tabs have a defined width.  I'd recommend setitng up your VSCode in this fashion for seeing correct indentation from files created in EMACS:

```json
    "[cm]": {
        "editor.detectIndentation": false,
        "editor.insertSpaces": true,
        "editor.tabSize": 8,
        "editor.indentSize": 4
    },
```
This sets the TAB size to be 8 spaces, and sets normal indent to be 4. (You can obviously use whatever numbers your team uses) but I would put the `tabSize` to be twice the amount of your `indentSize`.  If you have any questions please comment here happy to help!
