### ISSUE TITLE
Path to the CM root with CET GIT

### ISSUE THREAD

**Issue by MaRPriem** [docura-io/vscode-cm#56]
Hi,

CET added  the integration of GIT to their platform.
Because CET asked nicely I did what I suppose to do and I added a new GIT work-space.

After I did the installation I tried to connect the work-space with this extension with.
So I went to my cm Root and changed to path to "C:\CetDev\Release14_GIT".. But it didn't start
And this is not my first time changing work-spaces, We're doing it 1/2 times a week.
After trying multiple things (basically turning everything off and on like a true programmer) I found that they changed the whole order and locations in the GIT work-spaces.

So I think the CM extension can't find the launcher at the moment.  Because they changed the order of everything in the GIT work-space.

Could you guys please take a look at it? Or did I do something?
Please, I don't want to go back to Emacs. 

Thanks,

Remco

**Comment by kaestlyn** [comment]
Grab this from the release page: https://github.com/docura-io/vscode-cm/releases/tag/v1.4.0-beta2. 

I think we've worked out the kinks and soon will push this update to the store, but for now install it manually in vscode. From the extension pane click the menu button and choose install from vsix.

**Comment by MaRPriem** [comment]
You are a true legend! Thanks piet
