### ISSUE TITLE
Clean Workspace

### ISSUE THREAD

**Issue by fpmalard** [docura-io/vscode-cm#59]
In version 1.4.2, the command for cleaning CM files resulting from CMX preprocessing was removed.

Any chance to get it back?
It was useful to clean the workspace before backing the code up.

**Comment by kaestlyn** [comment]
I'm not aware of removing any commands related to this, the only commands that were removed were:

- "Purge Remote Cache" 
- "Set Arch 32-bit"
- "Set Arch 64-bit"

I've never used CMX files, can you give me a few simple steps on how to reproduce what you are seeing?  I'd like to try to do the same thing in EMACs to see if its a problem with how VSCode is invoke the clean command

I can see I tweaked how the clean command is sent to the compiler, it used to just run (where CM_HOME would point to your `bin` folder in your workspace):

```shell
make --jobs -C \"" + CM_HOME + "\" \"clean-cm\"
```

But with the migration to `Git` workspace support, I found a cmd (`base\bin\cmstarttestclean.cmd`) file that does this (which if I remember right, this is the CMD file the EMACs integration uses).

**Comment by kaestlyn** [comment]
In more recent versions, the clean command has been changed to be the same how EMACs handles this, it runs the `CM_HOME\bin\cmstarttestclean.cmd` file.  I think this should probably have corrected your issue.  If you didn't please let me know and I can try to look into it more.
