### ISSUE TITLE
Matching emacs features

### ISSUE THREAD

**Issue by tucaz** [docura-io/vscode-cm#75]
### Go to superclass method

In emacs, when `CTRL+C, CTRL+O` is used on top of an overridden method, it will take you to the original implementation on the parent class

**Comment by kaestlyn** [comment]
I believe the command `CM: Overrides` in VSCode does this bahvior:

![image](https://user-images.githubusercontent.com/1458549/124777496-dd908a80-df05-11eb-8dc1-7ae94ad242ed.png)

It invokes the following call to CM:
```
cm.runtime.overridesMethod("c:/CetDev/versiongit/extensions/Path/ToFile.cm", 1831)
```
_**EDIT**_ Pasted wrong image initially.
